/*
Fiber Example API

This is a sample swagger for Fiber

API version: 1.0
Contact: fiber@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UsersUserSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersUserSchema{}

// UsersUserSchema struct for UsersUserSchema
type UsersUserSchema struct {
	Avatar *string `json:"avatar,omitempty"`
	Bio *string `json:"bio,omitempty"`
	Email string `json:"email"`
	SubDragonId *int32 `json:"subDragonId,omitempty"`
	Username string `json:"username"`
}

// NewUsersUserSchema instantiates a new UsersUserSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersUserSchema(email string, username string) *UsersUserSchema {
	this := UsersUserSchema{}
	this.Email = email
	this.Username = username
	return &this
}

// NewUsersUserSchemaWithDefaults instantiates a new UsersUserSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersUserSchemaWithDefaults() *UsersUserSchema {
	this := UsersUserSchema{}
	return &this
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *UsersUserSchema) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserSchema) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *UsersUserSchema) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *UsersUserSchema) SetAvatar(v string) {
	o.Avatar = &v
}

// GetBio returns the Bio field value if set, zero value otherwise.
func (o *UsersUserSchema) GetBio() string {
	if o == nil || IsNil(o.Bio) {
		var ret string
		return ret
	}
	return *o.Bio
}

// GetBioOk returns a tuple with the Bio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserSchema) GetBioOk() (*string, bool) {
	if o == nil || IsNil(o.Bio) {
		return nil, false
	}
	return o.Bio, true
}

// HasBio returns a boolean if a field has been set.
func (o *UsersUserSchema) HasBio() bool {
	if o != nil && !IsNil(o.Bio) {
		return true
	}

	return false
}

// SetBio gets a reference to the given string and assigns it to the Bio field.
func (o *UsersUserSchema) SetBio(v string) {
	o.Bio = &v
}

// GetEmail returns the Email field value
func (o *UsersUserSchema) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UsersUserSchema) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UsersUserSchema) SetEmail(v string) {
	o.Email = v
}

// GetSubDragonId returns the SubDragonId field value if set, zero value otherwise.
func (o *UsersUserSchema) GetSubDragonId() int32 {
	if o == nil || IsNil(o.SubDragonId) {
		var ret int32
		return ret
	}
	return *o.SubDragonId
}

// GetSubDragonIdOk returns a tuple with the SubDragonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserSchema) GetSubDragonIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SubDragonId) {
		return nil, false
	}
	return o.SubDragonId, true
}

// HasSubDragonId returns a boolean if a field has been set.
func (o *UsersUserSchema) HasSubDragonId() bool {
	if o != nil && !IsNil(o.SubDragonId) {
		return true
	}

	return false
}

// SetSubDragonId gets a reference to the given int32 and assigns it to the SubDragonId field.
func (o *UsersUserSchema) SetSubDragonId(v int32) {
	o.SubDragonId = &v
}

// GetUsername returns the Username field value
func (o *UsersUserSchema) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UsersUserSchema) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UsersUserSchema) SetUsername(v string) {
	o.Username = v
}

func (o UsersUserSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersUserSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	if !IsNil(o.Bio) {
		toSerialize["bio"] = o.Bio
	}
	toSerialize["email"] = o.Email
	if !IsNil(o.SubDragonId) {
		toSerialize["subDragonId"] = o.SubDragonId
	}
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

type NullableUsersUserSchema struct {
	value *UsersUserSchema
	isSet bool
}

func (v NullableUsersUserSchema) Get() *UsersUserSchema {
	return v.value
}

func (v *NullableUsersUserSchema) Set(val *UsersUserSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersUserSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersUserSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersUserSchema(val *UsersUserSchema) *NullableUsersUserSchema {
	return &NullableUsersUserSchema{value: val, isSet: true}
}

func (v NullableUsersUserSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersUserSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


