/*
Fiber Example API

This is a sample swagger for Fiber

API version: 1.0
Contact: fiber@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the CommonCommonErrorSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonCommonErrorSchema{}

// CommonCommonErrorSchema struct for CommonCommonErrorSchema
type CommonCommonErrorSchema struct {
	Error *string `json:"error,omitempty"`
}

// NewCommonCommonErrorSchema instantiates a new CommonCommonErrorSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonCommonErrorSchema() *CommonCommonErrorSchema {
	this := CommonCommonErrorSchema{}
	return &this
}

// NewCommonCommonErrorSchemaWithDefaults instantiates a new CommonCommonErrorSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonCommonErrorSchemaWithDefaults() *CommonCommonErrorSchema {
	this := CommonCommonErrorSchema{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CommonCommonErrorSchema) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonCommonErrorSchema) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CommonCommonErrorSchema) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CommonCommonErrorSchema) SetError(v string) {
	o.Error = &v
}

func (o CommonCommonErrorSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonCommonErrorSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCommonCommonErrorSchema struct {
	value *CommonCommonErrorSchema
	isSet bool
}

func (v NullableCommonCommonErrorSchema) Get() *CommonCommonErrorSchema {
	return v.value
}

func (v *NullableCommonCommonErrorSchema) Set(val *CommonCommonErrorSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonCommonErrorSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonCommonErrorSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonCommonErrorSchema(val *CommonCommonErrorSchema) *NullableCommonCommonErrorSchema {
	return &NullableCommonCommonErrorSchema{value: val, isSet: true}
}

func (v NullableCommonCommonErrorSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonCommonErrorSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


