version: '3'

tasks:
  build:
    cmds:
      - swag init --parseDependency --output ./internal/pkg/swagger --parseInternal -g ./internal/routes/routes.go && go build .
  start:
    deps: [build]
    cmds:
      - go run .
  dev:
    deps: [build]
    cmds:
      - air
